version: '3.3'

services:
#  dev-mint-service:
#    build: ./
#    image:
#      solana-mint
#    environment:
#      ENVIRONMENT: dev
#      LISTEN_PORT: 5000
#    env_file:
#      - ./env.txt
#    container_name:
#      dev-solana-mint
#    ports:
#      - "6090:5000"
#    networks:
#      dev-network:
#        ipv4_address: 172.18.0.30
#    volumes:
#      - ./:/usr/src/app
#    restart: always

  dev-mint-redis:
    image:
      redis/redis-stack-server:latest
    container_name:
      dev-mint-redis
    ports:
      - "6379:6379"
    networks:
      dev-network:
        ipv4_address: 172.18.0.31
    restart: always


networks:
  dev-network:
    external: true
