version: '3.3'

services:
  user-service:
    build: ./
    image:
      fop-service
    environment:
      ENVIRONMENT: dev
      LISTEN_PORT: 5000
    env_file:
      - ./env.dev
    container_name:
      dev-fop
    ports:
      - "6051:5000"
    networks:
      dev-network:
        ipv4_address: 172.18.1.4
    volumes:
      - ./:/usr/src/app
    restart: always


networks:
  dev-network:
    external: true
